import { AspectRatioKey, RatioConfig, ThemeConfig, QuickPreset } from '../types';

export const RATIO_CONFIGS: Record<AspectRatioKey, RatioConfig> = {
  '1:1': {
    label: 'Square (1:1)',
    shortLabel: '1:1',
    description: 'Instagram & Profile',
    width: 1080,
    height: 1080,
    aspectClass: 'aspect-square',
  },
  '4:5': {
    label: 'Portrait (4:5)',
    shortLabel: '4:5',
    description: 'Instagram Feed Post',
    width: 1080,
    height: 1350,
    aspectClass: 'aspect-[4/5]',
  },
  '9:16': {
    label: 'Story / Reel (9:16)',
    shortLabel: '9:16',
    description: 'WhatsApp & TikTok',
    width: 1080,
    height: 1920,
    aspectClass: 'aspect-[9/16]',
  },
  '16:9': {
    label: 'Landscape (16:9)',
    shortLabel: '16:9',
    description: 'Desktop & Presentation',
    width: 1920,
    height: 1080,
    aspectClass: 'aspect-[16/9]',
  },
  '3:4': {
    label: 'Card (3:4)',
    shortLabel: '3:4',
    description: 'Pinterest & Wallpaper',
    width: 1200,
    height: 1600,
    aspectClass: 'aspect-[3/4]',
  },
};

export const THEMES: ThemeConfig[] = [
  {
    id: 'emerald',
    name: 'Emerald Royale',
    category: 'ornamental',
    bgClass: 'bg-gradient-to-br from-emerald-950 via-teal-900 to-slate-950',
    textClass: 'text-emerald-50',
    accentColor: '#10b981',
    borderDefault: 'border-emerald-500/40',
    badgeBg: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
  },
  {
    id: 'midnight',
    name: 'Midnight Indigo',
    category: 'dark',
    bgClass: 'bg-gradient-to-br from-slate-950 via-indigo-950 to-zinc-950',
    textClass: 'text-indigo-50',
    accentColor: '#818cf8',
    borderDefault: 'border-indigo-400/30',
    badgeBg: 'bg-indigo-500/20 text-indigo-300 border-indigo-500/30',
  },
  {
    id: 'gold',
    name: 'Desert Gold',
    category: 'ornamental',
    bgClass: 'bg-gradient-to-br from-amber-950 via-stone-900 to-neutral-950',
    textClass: 'text-amber-100',
    accentColor: '#fbbf24',
    borderDefault: 'border-amber-400/50',
    badgeBg: 'bg-amber-500/20 text-amber-300 border-amber-500/30',
  },
  {
    id: 'obsidian',
    name: 'Obsidian Minimal',
    category: 'dark',
    bgClass: 'bg-gradient-to-b from-neutral-900 to-black',
    textClass: 'text-neutral-100',
    accentColor: '#ffffff',
    borderDefault: 'border-neutral-700/60',
    badgeBg: 'bg-white/10 text-neutral-200 border-white/20',
  },
  {
    id: 'parchment',
    name: 'Vintage Parchment',
    category: 'light',
    bgClass: 'bg-gradient-to-br from-[#fbf8f1] via-[#f7f2e7] to-[#ede4d3]',
    textClass: 'text-stone-900',
    accentColor: '#78350f',
    borderDefault: 'border-stone-400/50',
    badgeBg: 'bg-stone-800/10 text-stone-800 border-stone-400/40',
  },
  {
    id: 'pearl',
    name: 'Clean Pearl',
    category: 'light',
    bgClass: 'bg-gradient-to-br from-white via-slate-50 to-slate-100',
    textClass: 'text-slate-800',
    accentColor: '#0f766e',
    borderDefault: 'border-slate-300',
    badgeBg: 'bg-emerald-600/10 text-emerald-800 border-emerald-600/20',
  },
  {
    id: 'crimson',
    name: 'Royal Ruby',
    category: 'ornamental',
    bgClass: 'bg-gradient-to-br from-rose-950 via-stone-950 to-black',
    textClass: 'text-rose-50',
    accentColor: '#f43f5e',
    borderDefault: 'border-rose-400/40',
    badgeBg: 'bg-rose-500/20 text-rose-300 border-rose-500/30',
  },
  {
    id: 'sapphire',
    name: 'Deep Ocean',
    category: 'dark',
    bgClass: 'bg-gradient-to-br from-cyan-950 via-blue-950 to-slate-950',
    textClass: 'text-cyan-50',
    accentColor: '#38bdf8',
    borderDefault: 'border-cyan-400/30',
    badgeBg: 'bg-cyan-500/20 text-cyan-300 border-cyan-500/30',
  },
];

export const POPULAR_SURAH_NUMBERS = [1, 2, 18, 36, 55, 67, 93, 94, 112, 113, 114];

export const QUICK_PRESETS: QuickPreset[] = [
  {
    id: 'kursi',
    label: 'Ayat al-Kursi',
    surahNumber: 2,
    surahName: 'Al-Baqarah',
    startAyah: 255,
    endAyah: 255,
    themeId: 'emerald',
    aspectRatio: '4:5',
  },
  {
    id: 'fatihah',
    label: 'Surah Al-Fatihah',
    surahNumber: 1,
    surahName: 'Al-Fatihah',
    startAyah: 1,
    endAyah: 7,
    themeId: 'gold',
    aspectRatio: '4:5',
  },
  {
    id: 'ikhlas',
    label: 'Surah Al-Ikhlas',
    surahNumber: 112,
    surahName: 'Al-Ikhlas',
    startAyah: 1,
    endAyah: 4,
    themeId: 'midnight',
    aspectRatio: '1:1',
  },
  {
    id: 'inshirah',
    label: 'Ash-Sharh (Ease after Hardship)',
    surahNumber: 94,
    surahName: 'Ash-Sharh',
    startAyah: 5,
    endAyah: 8,
    themeId: 'parchment',
    aspectRatio: '1:1',
  },
  {
    id: 'duha',
    label: 'Surah Ad-Duha',
    surahNumber: 93,
    surahName: 'Ad-Duha',
    startAyah: 1,
    endAyah: 5,
    themeId: 'obsidian',
    aspectRatio: '9:16',
  },
  {
    id: 'mulk',
    label: 'Al-Mulk (Opening)',
    surahNumber: 67,
    surahName: 'Al-Mulk',
    startAyah: 1,
    endAyah: 2,
    themeId: 'emerald',
    aspectRatio: '1:1',
  },
];
